# Generated by Django 5.1.2 on 2024-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourswalked',
            name='dateWalked',
            field=models.DateField(null=True),
        ),
    ]
